trigger:
- main

pool:
  vmImage: ubuntu-latest
  parallel: 1

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'mayaaiuga/waterstones-scraper'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'aks-service-connection'
    azureResourceGroup: 'aks-rg'
    kubernetesCluster: 'aks-demo'
    command: 'apply'
    secretType: 'generic'
    secretArguments: 'create secret generic gh-token --from-literal=encoded-value=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'
    secretName: 'gh-token'
