apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper-container
        image: mayaaiuga/test-scraper-image:latest
        env:
        - name: GH_TOKEN
          valueFrom:
            secretKeyRef:
              name: gh-token
              key: ghtoken


